
services:
  - type: web
    name: digitalisasi-silabus
    env: python
    buildCommand: |
      apt-get update && apt-get install -y wkhtmltopdf
      pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=10000
    plan: free
